language: node_js
env:
  global:
  - GH_REF=github.com/opengovt/openroads.git
  - DEPLOY_BRANCH=master
  - secure: OkfWr+DDlOW8h3FLcPWRNQqaRzBltDxC24voLuvf666LVjx8HzJryc9m8xRMGjJGwhP+UNJmLiuAbIPkrQU542MtpYoFnKKAMJbKicwjyGwb+sdr2srMvRQ1BDk6b0AcHK0dUSvUcp0JUJVcJ3caTNlkmz00pwz4GnTF+DpKdnA=

before_install:
- chmod +x ./.build_scripts/deploy.sh

script:
- echo No test specified

after_success:
- ./.build_scripts/deploy.sh
